- name: create aws ec2 and r53 records
  hosts: localhost
  vars:
    zone: muvva.online
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type:  t2.micro
      security_group: allow_everything
      image_id: ami-090252cbe067a9e58
      tags:
        Name: "{{ item }}"
    loop:
    - db
    - backend
    - frontend
    register: ec2_instanes_output

  # - name: creating r53 records
  #   amazon.aws.route53:
  #     record: 
