- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: delete default directory of html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating the directory html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory     #state shoukd be directory for creating the same

- name: download and unarchive the code in html folder of remote server
  ansible.builtin.unarchive:
    src:  https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy expense.conf (backend conf) to frontend server
  ansible.builtin.template:
    src: expense.conf.j2 
    dest: /etc/nginx/default.d/expense.conf 
  notify:
  - restart nginx

# - name: restart nginx #restart service only, when config changes, so moving this code to handlers
#   ansible.builtin.service:
#     name: nginx
#     state: restarted
